'use client'

import { useEffect, useState, useCallback } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { trainModel, compareModels, graphUrl, predictWithModel } from '@/lib/api'
import type { TrainingResult, CompareSession, CompareResult, SingleModelGraphs, ComparisonGraphs, PredictResult } from '@/lib/api'
import { useRouter } from 'next/navigation'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------
interface UploadedFile {
  name: string
  filepath: string
  columns: string[]
  rowCount: number
}

interface StoredModelSession extends CompareSession {
  modelName: string
  graphs: TrainingResult['graphs']
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------
const MODELS = [
  { id: 'linear_regression', name: 'Linear Regression', description: 'Best for linear relationships' },
  { id: 'random_forest',     name: 'Random Forest',     description: 'Good for complex non-linear patterns' },
  { id: 'svm',               name: 'Support Vector Machine', description: 'Effective for both regression and classification' },
]

const GRAPH_LABELS: Record<string, string> = {
  line:                 'Actual vs Predicted (Line)',
  scatter:              'Actual vs Predicted (Scatter)',
  error_histogram:      'Error Distribution',
  comparison_r2:        'R² Score Comparison',
  comparison_rmse_mae:  'RMSE & MAE Comparison',
  comparison_scatter:   'All Models — Combined Scatter',
}

// ---------------------------------------------------------------------------
// Small helper components
// ---------------------------------------------------------------------------

function GraphImage({ filename, label }: { filename: string; label: string }) {
  const [loaded, setLoaded] = useState(false)
  const [errored, setErrored] = useState(false)
  const url = graphUrl(filename)

  if (errored) {
    return (
      <div className="flex items-center justify-center h-40 rounded-lg border border-dashed border-muted-foreground/30 text-sm text-muted-foreground">
        Could not load graph.
      </div>
    )
  }

  return (
    <div>
      <p className="text-sm font-medium text-muted-foreground mb-2">{label}</p>
      {!loaded && (
        <div className="flex items-center justify-center h-40 rounded-lg border border-dashed border-muted-foreground/30 text-sm text-muted-foreground animate-pulse">
          Loading graph…
        </div>
      )}
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={url}
        alt={label}
        className={`w-full rounded-lg border border-border shadow-sm transition-opacity duration-300 ${loaded ? 'opacity-100' : 'opacity-0 h-0'}`}
        onLoad={() => setLoaded(true)}
        onError={() => setErrored(true)}
      />
    </div>
  )
}

function GraphGrid({ graphs, title }: { graphs: SingleModelGraphs | ComparisonGraphs; title: string }) {
  const entries = Object.entries(graphs) as [string, string][]
  if (entries.length === 0) return null

  return (
    <Card>
      <CardHeader>
        <CardTitle>{title}</CardTitle>
        <CardDescription>Generated by Matplotlib after training</CardDescription>
      </CardHeader>
      <CardContent>
        <div className={`grid gap-6 ${entries.length === 1 ? 'grid-cols-1' : 'md:grid-cols-2 lg:grid-cols-3'}`}>
          {entries.map(([key, filename]) => (
            <GraphImage key={key} filename={filename} label={GRAPH_LABELS[key] ?? key} />
          ))}
        </div>
      </CardContent>
    </Card>
  )
}

// ---------------------------------------------------------------------------
// Storage helpers (sessionStorage)
// ---------------------------------------------------------------------------
const SESSION_KEY = 'mlTrainedSessions'

function loadStoredSessions(): StoredModelSession[] {
  try {
    const raw = sessionStorage.getItem(SESSION_KEY)
    return raw ? JSON.parse(raw) : []
  } catch {
    return []
  }
}

function saveStoredSessions(sessions: StoredModelSession[]) {
  sessionStorage.setItem(SESSION_KEY, JSON.stringify(sessions))
}

// ---------------------------------------------------------------------------
// Main page
// ---------------------------------------------------------------------------
export default function MLIntegrationPage() {
  const router = useRouter()

  const [isLoading,   setIsLoading]   = useState(true)
  const [isTraining,  setIsTraining]  = useState(false)
  const [isComparing, setIsComparing] = useState(false)
  const [error,       setError]       = useState<string>('')

  const [uploadedFile,     setUploadedFile]     = useState<UploadedFile | null>(null)
  const [selectedFeatures, setSelectedFeatures] = useState<string[]>([])
  const [selectedTarget,   setSelectedTarget]   = useState<string>('')
  const [selectedModel,    setSelectedModel]    = useState<string>('')

  const [trainingResults,  setTrainingResults]  = useState<TrainingResult | null>(null)
  const [compareResult,    setCompareResult]    = useState<CompareResult | null>(null)
  const [trainedSessions,  setTrainedSessions]  = useState<StoredModelSession[]>([])

  // Prediction (user input test)
  const [predictionInputs, setPredictionInputs] = useState<Record<string, string>>({})
  const [predictionResult, setPredictionResult] = useState<PredictResult | null>(null)
  const [isPredicting,     setIsPredicting]     = useState(false)
  const [predictionError,  setPredictionError]  = useState<string>('')

  // Load file meta + previous sessions on mount
  useEffect(() => {
    const fileData = sessionStorage.getItem('uploadedFile')
    if (!fileData) {
      setError('No file uploaded')
      setIsLoading(false)
      return
    }
    try {
      const file = JSON.parse(fileData) as UploadedFile
      if (!file.columns || !Array.isArray(file.columns) || file.columns.length === 0) {
        setError('File data is incomplete. Please re-upload your file.')
        setIsLoading(false)
        return
      }
      setUploadedFile(file)
      setTrainedSessions(loadStoredSessions())
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load file data')
    } finally {
      setIsLoading(false)
    }
  }, [])

  const handleFeatureToggle = (feature: string) => {
    setSelectedFeatures(prev =>
      prev.includes(feature) ? prev.filter(f => f !== feature) : [...prev, feature]
    )
  }

  const handleTrainModel = async () => {
    if (!uploadedFile || !selectedModel || selectedFeatures.length === 0 || !selectedTarget) {
      setError('Please select model, features, and target variable')
      return
    }
    if (selectedFeatures.includes(selectedTarget)) {
      setError('Target variable cannot be in features')
      return
    }

    setIsTraining(true)
    setError('')
    setCompareResult(null)

    try {
      const results = await trainModel(uploadedFile.filepath, selectedModel, selectedFeatures, selectedTarget)
      setTrainingResults(results)

      // Persist this session for comparison later
      const newSession: StoredModelSession = {
        session_id: results.session_id,
        model_type: results.model_type,
        modelName:  MODELS.find(m => m.id === results.model_type)?.name ?? results.model_type,
        metrics:    results.metrics,
        graphs:     results.graphs,
      }
      const updated = [
        ...trainedSessions.filter(s => s.model_type !== results.model_type),
        newSession,
      ]
      setTrainedSessions(updated)
      saveStoredSessions(updated)

    } catch (err) {
      setError(err instanceof Error ? err.message : 'Model training failed')
    } finally {
      setIsTraining(false)
    }
  }

  const handleCompare = useCallback(async () => {
    if (trainedSessions.length < 2) return
    setIsComparing(true)
    setError('')
    try {
      const result = await compareModels(
        trainedSessions.map(s => ({
          session_id: s.session_id,
          model_type: s.model_type,
          metrics:    s.metrics,
        }))
      )
      setCompareResult(result)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Comparison failed')
    } finally {
      setIsComparing(false)
    }
  }, [trainedSessions])

  const handleReset = () => {
    setTrainingResults(null)
    setCompareResult(null)
    setSelectedModel('')
    setSelectedFeatures([])
    setSelectedTarget('')
    setError('')
    setPredictionInputs({})
    setPredictionResult(null)
    setPredictionError('')
  }

  const handleClearHistory = () => {
    sessionStorage.removeItem(SESSION_KEY)
    setTrainedSessions([])
    setCompareResult(null)
  }

  const handlePredict = async () => {
    if (!trainingResults) return
    setPredictionError('')
    setPredictionResult(null)

    // Validate — all feature inputs must be filled and numeric
    const numericInputs: Record<string, number> = {}
    for (const feature of selectedFeatures) {
      const raw = predictionInputs[feature]?.trim() ?? ''
      if (raw === '') {
        setPredictionError(`Please enter a value for "${feature}"`)
        return
      }
      const parsed = Number(raw)
      if (isNaN(parsed)) {
        setPredictionError(`"${feature}" must be a number`)
        return
      }
      numericInputs[feature] = parsed
    }

    setIsPredicting(true)
    try {
      const result = await predictWithModel(trainingResults.session_id, numericInputs)
      setPredictionResult(result)
    } catch (err) {
      setPredictionError(err instanceof Error ? err.message : 'Prediction failed')
    } finally {
      setIsPredicting(false)
    }
  }

  // ------------------------------------------------------------------
  // Loading / error states
  // ------------------------------------------------------------------
  if (isLoading) {
    return (
      <div className="p-6 text-center">
        <p className="text-muted-foreground">Loading…</p>
      </div>
    )
  }

  if (error && !trainingResults) {
    return (
      <div className="p-6 space-y-4">
        <div className="rounded-lg bg-red-50 p-4 border border-red-200">
          <p className="text-red-900 font-medium">Error: {error}</p>
        </div>
        {error.includes('re-upload') && (
          <Button onClick={() => {
            sessionStorage.removeItem('uploadedFile')
            router.push('/dashboard/upload')
          }}>
            Go to Upload Page
          </Button>
        )}
      </div>
    )
  }

  // ------------------------------------------------------------------
  // Render
  // ------------------------------------------------------------------
  return (
    <div className="space-y-6 p-6">
      <section>
        <h2 className="text-3xl font-bold text-foreground">ML Model Training</h2>
        <p className="mt-2 text-muted-foreground">
          Train machine learning models to predict outcomes
        </p>
      </section>

      {error && (
        <div className="rounded-lg bg-red-50 p-4 border border-red-200">
          <p className="text-red-900 text-sm">{error}</p>
        </div>
      )}

      {/* Previously trained sessions banner */}
      {trainedSessions.length > 0 && (
        <Card className="border-blue-200 bg-blue-50">
          <CardContent className="pt-4 pb-4">
            <div className="flex flex-wrap items-center gap-3">
              <span className="text-sm font-medium text-blue-900">
                {trainedSessions.length} model{trainedSessions.length > 1 ? 's' : ''} trained this session:
              </span>
              {trainedSessions.map(s => (
                <Badge key={s.session_id} variant="secondary">{s.modelName}</Badge>
              ))}
              {trainedSessions.length >= 2 && (
                <Button
                  size="sm"
                  variant="outline"
                  className="ml-auto border-blue-300 text-blue-900 hover:bg-blue-100"
                  onClick={handleCompare}
                  disabled={isComparing}
                >
                  {isComparing ? 'Generating…' : 'Compare Models'}
                </Button>
              )}
              <Button
                size="sm"
                variant="ghost"
                className="text-blue-700 hover:text-blue-900"
                onClick={handleClearHistory}
              >
                Clear history
              </Button>
            </div>
          </CardContent>
        </Card>
      )}

      {!trainingResults ? (
        <>
          {/* ---- Model Selection ---- */}
          <Card>
            <CardHeader>
              <CardTitle>Select Model</CardTitle>
              <CardDescription>Choose the machine learning model to train</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid gap-4 md:grid-cols-3">
                {MODELS.map(model => (
                  <button
                    key={model.id}
                    onClick={() => setSelectedModel(model.id)}
                    className={`p-4 rounded-lg border-2 text-left transition-all ${
                      selectedModel === model.id
                        ? 'border-primary bg-primary/5'
                        : 'border-border hover:border-muted-foreground/50'
                    }`}
                  >
                    <h4 className="font-medium text-foreground">{model.name}</h4>
                    <p className="text-sm text-muted-foreground mt-1">{model.description}</p>
                  </button>
                ))}
              </div>
            </CardContent>
          </Card>

          {/* ---- Feature Selection ---- */}
          {uploadedFile && (
            <Card>
              <CardHeader>
                <CardTitle>Select Features</CardTitle>
                <CardDescription>Choose columns to use as input features</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">
                  {uploadedFile.columns.map(col => (
                    <button
                      key={col}
                      onClick={() => handleFeatureToggle(col)}
                      disabled={col === selectedTarget}
                      className={`p-3 rounded-lg border-2 text-left transition-all disabled:opacity-50 disabled:cursor-not-allowed ${
                        selectedFeatures.includes(col)
                          ? 'border-primary bg-primary/5'
                          : 'border-border hover:border-muted-foreground/50'
                      }`}
                    >
                      <div className="flex items-center justify-between">
                        <span className="font-medium text-foreground">{col}</span>
                        {selectedFeatures.includes(col) && <span className="text-primary">✓</span>}
                      </div>
                    </button>
                  ))}
                </div>
                <p className="text-sm text-muted-foreground mt-4">
                  Selected: {selectedFeatures.length} feature{selectedFeatures.length !== 1 ? 's' : ''}
                </p>
              </CardContent>
            </Card>
          )}

          {/* ---- Target Variable Selection ---- */}
          {uploadedFile && (
            <Card>
              <CardHeader>
                <CardTitle>Select Target Variable</CardTitle>
                <CardDescription>Choose the variable to predict</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">
                  {uploadedFile.columns.map(col => (
                    <button
                      key={col}
                      onClick={() => setSelectedTarget(col)}
                      className={`p-3 rounded-lg border-2 text-left transition-all ${
                        selectedTarget === col ? 'border-primary bg-primary/5' : 'border-border hover:border-muted-foreground/50'
                      }`}
                    >
                      <div className="flex items-center justify-between">
                        <span className="font-medium text-foreground">{col}</span>
                        {selectedTarget === col && <span className="text-primary">✓</span>}
                      </div>
                    </button>
                  ))}
                </div>
              </CardContent>
            </Card>
          )}

          {/* ---- Training Controls ---- */}
          <div className="flex gap-4">
            <Button
              onClick={handleTrainModel}
              disabled={isTraining || !selectedModel || selectedFeatures.length === 0 || !selectedTarget}
              size="lg"
              className="flex-1"
            >
              {isTraining ? 'Training Model…' : 'Start Training'}
            </Button>
          </div>
        </>
      ) : (
        <>
          {/* ---- Training Results ---- */}
          <Card className="border-green-200 bg-green-50">
            <CardContent className="pt-6">
              <p className="text-green-900 font-medium">✓ Model training completed successfully!</p>
            </CardContent>
          </Card>

          {/* ---- Model Information ---- */}
          <div className="grid gap-4 md:grid-cols-2">
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm font-medium text-muted-foreground">Model Type</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-lg font-bold text-foreground">
                  {MODELS.find(m => m.id === selectedModel)?.name}
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm font-medium text-muted-foreground">Training Samples</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-lg font-bold text-foreground">{trainingResults.training_samples.toLocaleString()}</div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm font-medium text-muted-foreground">Test Samples</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-lg font-bold text-foreground">{trainingResults.test_samples.toLocaleString()}</div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm font-medium text-muted-foreground">Test R² Score</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-lg font-bold text-foreground">
                  {(trainingResults.metrics.test.r2 * 100).toFixed(2)}%
                </div>
              </CardContent>
            </Card>
          </div>

          {/* ---- Performance Metrics ---- */}
          <Card>
            <CardHeader>
              <CardTitle>Performance Metrics</CardTitle>
              <CardDescription>Training and testing metrics</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid gap-6 md:grid-cols-2">
                <div className="space-y-3">
                  <h4 className="font-medium text-foreground">Training Metrics</h4>
                  <div className="space-y-2 text-sm">
                    {(['mse', 'rmse', 'mae', 'r2'] as const).map(k => (
                      <div key={k} className="flex justify-between">
                        <span className="text-muted-foreground">{k.toUpperCase()}:</span>
                        <span className="font-medium">{trainingResults.metrics.train[k].toFixed(4)}</span>
                      </div>
                    ))}
                  </div>
                </div>
                <div className="space-y-3">
                  <h4 className="font-medium text-foreground">Testing Metrics</h4>
                  <div className="space-y-2 text-sm">
                    {(['mse', 'rmse', 'mae', 'r2'] as const).map(k => (
                      <div key={k} className="flex justify-between">
                        <span className="text-muted-foreground">{k.toUpperCase()}:</span>
                        <span className="font-medium">{trainingResults.metrics.test[k].toFixed(4)}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* ---- Per-Model Graphs ---- */}
          <GraphGrid
            graphs={trainingResults.graphs}
            title={`${MODELS.find(m => m.id === selectedModel)?.name} — Performance Graphs`}
          />

          {/* ---- Feature Importance ---- */}
          {trainingResults.feature_importance && (
            <Card>
              <CardHeader>
                <CardTitle>Feature Importance</CardTitle>
                <CardDescription>How important each feature is for predictions</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  {Object.entries(trainingResults.feature_importance).map(([feature, importance]) => (
                    <div key={feature}>
                      <div className="flex justify-between mb-1">
                        <span className="text-sm font-medium text-foreground">{feature}</span>
                        <span className="text-sm text-muted-foreground">{(importance * 100).toFixed(1)}%</span>
                      </div>
                      <div className="w-full bg-muted rounded-full h-2">
                        <div className="bg-primary h-2 rounded-full" style={{ width: `${importance * 100}%` }} />
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          )}

          {/* ---- Sample Predictions ---- */}
          <Card>
            <CardHeader>
              <CardTitle>Sample Predictions</CardTitle>
              <CardDescription>First 20 predictions on test set</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="overflow-x-auto">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Actual</TableHead>
                      <TableHead>Predicted</TableHead>
                      <TableHead>Error</TableHead>
                      <TableHead>Error %</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {trainingResults.predictions.map((pred, idx) => (
                      <TableRow key={idx}>
                        <TableCell>{pred.actual.toFixed(2)}</TableCell>
                        <TableCell>{pred.predicted.toFixed(2)}</TableCell>
                        <TableCell className={pred.error < 0 ? 'text-green-600' : 'text-red-600'}>
                          {pred.error.toFixed(2)}
                        </TableCell>
                        <TableCell>{Math.abs(pred.error_percentage).toFixed(2)}%</TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>
            </CardContent>
          </Card>

          {/* ---- Test the Model — User Input ---- */}
          <Card>
            <CardHeader>
              <CardTitle>Test the Model</CardTitle>
              <CardDescription>
                Enter feature values to get a live prediction from the trained model
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-5">
              {/* Feature input grid */}
              <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                {selectedFeatures.map(feature => (
                  <div key={feature} className="space-y-1">
                    <label className="text-sm font-medium text-foreground">{feature}</label>
                    <input
                      type="number"
                      step="any"
                      placeholder="Enter value"
                      value={predictionInputs[feature] ?? ''}
                      onChange={e =>
                        setPredictionInputs(prev => ({ ...prev, [feature]: e.target.value }))
                      }
                      className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm shadow-sm placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:border-transparent"
                    />
                  </div>
                ))}
              </div>

              {/* Prediction error */}
              {predictionError && (
                <div className="rounded-md bg-red-50 border border-red-200 px-4 py-2 text-sm text-red-800">
                  {predictionError}
                </div>
              )}

              {/* Predict button */}
              <Button
                onClick={handlePredict}
                disabled={isPredicting || selectedFeatures.length === 0}
                className="w-full sm:w-auto"
              >
                {isPredicting ? 'Predicting…' : 'Run Prediction'}
              </Button>

              {/* Result display */}
              {predictionResult && (
                <div className="rounded-lg border-2 border-primary/30 bg-primary/5 p-5 space-y-3">
                  <p className="text-sm font-medium text-muted-foreground">Predicted Value</p>
                  <p className="text-4xl font-extrabold text-primary">
                    {predictionResult.predicted_value.toLocaleString(undefined, {
                      minimumFractionDigits: 2,
                      maximumFractionDigits: 4,
                    })}
                  </p>
                  <p className="text-xs text-muted-foreground">
                    Target: <span className="font-medium text-foreground">{selectedTarget}</span>
                    &nbsp;·&nbsp;Model:{' '}
                    <span className="font-medium text-foreground">
                      {MODELS.find(m => m.id === selectedModel)?.name}
                    </span>
                  </p>
                  {/* Recap of inputs used */}
                  <details className="text-xs text-muted-foreground">
                    <summary className="cursor-pointer select-none hover:text-foreground">
                      View inputs used
                    </summary>
                    <div className="mt-2 grid gap-1 sm:grid-cols-2 lg:grid-cols-3">
                      {Object.entries(predictionResult.input_used).map(([k, v]) => (
                        <div key={k} className="flex justify-between gap-2 rounded bg-muted/50 px-2 py-1">
                          <span className="font-medium text-foreground">{k}</span>
                          <span>{v}</span>
                        </div>
                      ))}
                    </div>
                  </details>
                </div>
              )}
            </CardContent>
          </Card>

          {/* ---- Comparison Graphs (shown if compare was run) ---- */}
          {compareResult && (
            <GraphGrid
              graphs={compareResult.graphs}
              title="Model Comparison Charts"
            />
          )}

          {/* ---- Action Buttons ---- */}
          <div className="flex flex-wrap gap-4">
            <Button onClick={handleReset} variant="outline" size="lg" className="flex-1">
              Train Another Model
            </Button>
            {trainedSessions.length >= 2 && !compareResult && (
              <Button
                onClick={handleCompare}
                disabled={isComparing}
                size="lg"
                className="flex-1"
              >
                {isComparing ? 'Generating Comparison…' : 'Compare All Trained Models'}
              </Button>
            )}
            {compareResult && (
              <Button
                onClick={handleCompare}
                disabled={isComparing}
                variant="secondary"
                size="lg"
              >
                {isComparing ? 'Refreshing…' : 'Refresh Comparison'}
              </Button>
            )}
          </div>
        </>
      )}
    </div>
  )
}
